{% set name = "disk-objectstore" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace('-','_') }}-{{ version }}.tar.gz
  sha256: a61e3a817e2552fc834a61aaba975708ab1342b3bee4d3bdd6e3fc69de5177db

build:
  number: 0
  entry_points:
    - dostore = disk_objectstore.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8
    - click
    - sqlalchemy >=1.4.22

test:
  requires:
    - pip
  imports:
    - disk_objectstore
    - disk_objectstore.examples
  commands:
   - pip check
   - dostore --help

about:
  home: http://github.com/aiidateam/disk-objectstore
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: An implementation of an efficient object store writing directly into a disk folder

extra:
  recipe-maintainers:
    - chrisjsewell
    - sphuber
