{% set name = "disk-objectstore" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace('-','_') }}-{{ version }}.tar.gz
  sha256: ad3404eff452eacb2cf3fcd25d45cfc933eb32b4fd69fba81f4c3cbda47b1777

build:
  number: 0
  entry_points:
    - dostore = disk_objectstore.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - click
    - sqlalchemy ~=1.4.22
    - typing-extensions

test:
  requires:
    - pip
  imports:
    - disk_objectstore
    - disk_objectstore.examples
  commands:
   - pip check
   - dostore --help

about:
  home: http://github.com/aiidateam/disk-objectstore
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: An implementation of an efficient object store writing directly into a disk folder

extra:
  recipe-maintainers:
    - chrisjsewell
